version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Indianapolis"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "America/Indianapolis"
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    groups:
      client-production:
        dependency-type: "production"
        patterns:
          - "*"
      client-development:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "America/Indianapolis"
    open-pull-requests-limit: 5
    groups:
      api-python:
        patterns:
          - "*"
